# Generated by Django 3.0.8 on 2020-07-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
